import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main className="min-h-screen  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto mt-14 max-w-7xl">
        <div className="flex flex-col justify-between items-top md:flex-row">
          <div className="flex flex-col space-y-5 w-full md:w-1/2">
            <h1 className="text-7xl font-bold lowercase tracking-wide text-white leading-none">
              your favourite characters in, new
              <span className="text-rose-500"> cyberpunk style</span>
            </h1>
          </div>
          <div className="w-full md:w-1/2 flex justify-end">
            <Image
              src="https://cdn.discordapp.com/attachments/1066511950047084564/1069280098701819975/Obra_ellie_from_the_last_of_us_in_cyberpunk_style_7cdd8756-0290-46df-9089-54b4696230fa.png"
              alt="main image"
              width={500}
              height={500}
              className="rounded-2xl  shadow-[5px_5px_0px_0px_#fde68a]"
            />
          </div>
        </div>
      </section>
    </main>
  );
}
