import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import { useEffect, useState } from "react";
import { useStateContext } from "../context";
import { DisplayNfts } from "../components";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [nfts, setNfts] = useState([]);

  const { address, contract, getNFTs } = useStateContext();

  const fetchNFTs = async () => {
    setIsLoading(true);
    const data = await getNFTs();

    setNfts(data);
    setIsLoading(false);
  };

  useEffect(() => {
    if (contract) fetchNFTs();
  }, [address, contract]);

  return (
    <main className="min-h-screen  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      {/* <Hero /> */}

      <section className="container mx-auto mt-14 ">
        <div className="flex flex-col justify-between items-center  ">
          <div className="w-3/5 flex flex-col justify-center items-center mx-auto lowercase my-28 ">
            <h1 className="text-8xl text-center font-bold lowercase tracking-wide text-white leading-none">
              your favourite characters in, new
              <span className="text-rose-500"> cyberpunk style</span>
            </h1>
          </div>

          <div className="w-full  flex justify-end h-screen">
            <Image
              src="https://cdn.discordapp.com/attachments/1066511950047084564/1069280098701819975/Obra_ellie_from_the_last_of_us_in_cyberpunk_style_7cdd8756-0290-46df-9089-54b4696230fa.png"
              alt="main image"
              width={1500}
              height={1500}
              className="rounded-2xl object-cover w-full h-3/5  max-h-3/5 object-center"
            />
          </div>
        </div>
      </section>

      <section className="container mx-auto my-14">
        <div className="flex flex-col justify-between items-top md:flex-row max-w-7xl mx-auto">
          <DisplayNfts nfts={nfts} />
        </div>
      </section>
    </main>
  );
}
