import { useRouter } from "next/router";
import { useStateContext } from "../../context";
import { useEffect, useState } from "react";
import Head from "next/head";
import { Footer, Navbar } from "../../components";
import Image from "next/image";

export default function SingleNFT() {
  const router = useRouter();
  const [NFT, setNFT] = useState([]);

  const { getSingleNFT, address, contract, buyNFT, connect } =
    useStateContext();
  const { nftID } = router.query;

  const fetchNFT = async () => {
    const data = await getSingleNFT(nftID);
    setNFT(data);
  };

  useEffect(() => {
    if (contract) fetchNFT();
  }, [address, contract]);

  console.log(NFT);
  return (
    <main className=" ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto mt-14 max-h-screen">
        <div className="flex flex-col justify-between items-top md:flex-row  mx-auto space-x-10  h-screen">
          <div className="flex w-1/2 h-2/3">
            <Image
              src={NFT.image}
              alt={NFT.name}
              width={1000}
              height={750}
              className="w-full h-full object-cover rounded-3xl shadow-[0_20px_50px_rgba(109,_40,_217,_0.15)]"
            />
          </div>
          <div className="flex flex-col  h-1/5 justify-between items-start  w-1/2">
            <h1 className="text-6xl  font-bold  tracking-wide text-white leading-none text-left ">
              {NFT.name}
            </h1>

            <div className="flex mt-5 space-x-5">
              <Image
                src="/images/ellie3.png"
                alt="Owner Icon"
                height={50}
                width={50}
                className="rounded-full"
              />
              <p className="text-2xl text-left font-bold  tracking-wide text-gray-500 leading-none mt-4 pr-10">
                {NFT.owner}
              </p>
            </div>

            <div className="border-2 border-rose-500 w-full my-5 shadow-[0_20px_50px_rgba(225,_29,_72,_0.6)]"></div>

            <p className="text-2xl text-left font-bold  tracking-wide text-gray-200 leading-none mt-4 pr-10">
              {NFT.description}
            </p>
            <p className="text-2xl text-left font-bold  tracking-wide text-gray-500 leading-none mt-4 pr-10">
              Price: {NFT.price} <span className="text-violet-600">ETH</span>
            </p>

            {!address ? (
              <button
                className="border-2 border-blue-600 shadow-2xl shadow-blue-500/30 text-white font-bold py-4 px-10 rounded-full mt-10 w-fit hover:bg-blue-600 hover:shadow-blue-500/60 duration-300 transition-all"
                onClick={() => connect()}
              >
                Connect
              </button>
            ) : (
              <button
                className="border-2 border-rose-600 shadow-2xl shadow-rose-500/30 text-white font-bold py-4 px-10 rounded-full mt-10 w-fit hover:bg-rose-600 hover:shadow-rose-500/60 duration-300 transition-all"
                onClick={() => buyNFT(nftID)}
              >
                Buy
              </button>
            )}
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
