import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import { useEffect, useState } from "react";
import { useStateContext } from "../../context";
import { DisplayNfts, Footer } from "../../components";
import Link from "next/link";

export default function NFTS() {
  const [isLoading, setIsLoading] = useState(false);
  const [nfts, setNfts] = useState([]);

  const { address, contract, getExploreNFTs } = useStateContext();

  const fetchNFTs = async () => {
    setIsLoading(true);
    const data = await getExploreNFTs();

    setNfts(data);
    setIsLoading(false);
  };

  useEffect(() => {
    if (contract) fetchNFTs();
  }, [address, contract]);

  return (
    <main className="min-h-screen relative ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container mx-auto my-10">
        <div className="flex flex-col justify-between items-top  ">
          <h1 className="text-4xl text-center md:text-6xl lg:text-8xl  font-bold  tracking-wide text-white leading-none lg:text-left">
            Explore our NFTs from <br></br>{" "}
            <span className="text-rose-700 ">cyberpunk</span> collection
          </h1>
          <div className="mt-20">
            <DisplayNfts nfts={nfts} />
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
